# Generated by Django 5.1.3 on 2025-08-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Midia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("imagem", "Imagem"),
                            ("audio", "Áudio"),
                            ("video", "Vídeo"),
                        ],
                        max_length=10,
                    ),
                ),
                ("arquivo", models.FileField(upload_to="midias/")),
            ],
        ),
    ]
