# Generated by Django 5.1.3 on 2025-08-21 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("denuncia", "0001_initial"),
        ("midia", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MidiaDenuncia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conteudo", models.FileField(upload_to="provas_denuncias/")),
                (
                    "denuncia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provas",
                        to="denuncia.denuncia",
                    ),
                ),
                (
                    "midia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="midia.midia"
                    ),
                ),
            ],
        ),
    ]
