# Generated by Django 5.1.3 on 2025-09-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="setor",
            field=models.CharField(
                choices=[
                    ("CA", "Coordenação de Ensino"),
                    ("CAE", "Coordenação de Assuntos Estudantis"),
                    ("Diretoria Academica", "Diretoria Acadêmica"),
                    ("Administrativo", "Administrativo"),
                    (
                        "NAPNE",
                        "Núcleo de Atendimento a Pessoas com Necessidades Específicas",
                    ),
                    ("Outro", "Outro"),
                ],
                default="OUT",
                max_length=100,
            ),
        ),
    ]
