# Generated by Django 5.1.4 on 2025-06-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=1000)),
                ('envolvidos', models.CharField(max_length=100)),
                ('tipo_abuso', models.CharField(max_length=100)),
                ('provas', models.FileField(blank=True, null=True, upload_to='provas/')),
                ('data_acontecimento', models.DateField()),
                ('local', models.CharField(max_length=100)),
            ],
        ),
    ]
