# Generated by Django 5.1.3 on 2025-08-12 12:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categoria", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DescricaoDenuncia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_ocorrido", models.DateTimeField()),
                ("descricao", models.TextField()),
                ("envolvidos", models.CharField(blank=True, max_length=255)),
                ("local_ocorrido", models.CharField(max_length=255)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="categoria.categoria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Denuncia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_envio", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("nova", "Nova"),
                            ("em_andamento", "Em Andamento"),
                            ("finalizada", "Finalizada"),
                            ("arquivada", "Arquivada"),
                        ],
                        default="nova",
                        max_length=20,
                    ),
                ),
                (
                    "usuario_anonimo",
                    models.CharField(
                        blank=True,
                        help_text="Preencha se a denúncia for anônima",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("data_cancelamento", models.DateTimeField(blank=True, null=True)),
                ("data_finalizacao", models.DateTimeField(blank=True, null=True)),
                (
                    "codigo_acompanhamento",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, null=True, unique=True
                    ),
                ),
                (
                    "gerenciada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "descricao_denuncia",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="denuncia.descricaodenuncia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TipoProva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audio",
                    models.FileField(blank=True, null=True, upload_to="provas/audios/"),
                ),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="provas/fotos/"),
                ),
                (
                    "video",
                    models.FileField(blank=True, null=True, upload_to="provas/videos/"),
                ),
                (
                    "denuncia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provas",
                        to="denuncia.denuncia",
                    ),
                ),
            ],
        ),
    ]
