# Generated by Django 5.1.3 on 2025-08-21 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categoria", "__first__"),
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Denuncia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField()),
                ("dt_envio", models.DateTimeField(auto_now_add=True)),
                (
                    "codigo_rastreamento",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Código único para o denunciante acompanhar o status.",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recebida", "Recebida"),
                            ("em_andamento", "Em Andamento"),
                            ("finalizada", "Finalizada"),
                            ("arquivada", "Arquivada"),
                        ],
                        default="nova",
                        max_length=20,
                    ),
                ),
                (
                    "dt_ocorrido",
                    models.DateTimeField(verbose_name="Data e Hora do Ocorrido"),
                ),
                ("local", models.CharField(max_length=255)),
                ("dt_fim", models.DateField(blank=True, null=True)),
                (
                    "envolvidos",
                    models.TextField(
                        blank=True,
                        help_text="Descreva os envolvidos na denúncia, se houver.",
                        null=True,
                    ),
                ),
                ("desfecho", models.TextField(blank=True, null=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="denuncias",
                        to="categoria.categoria",
                    ),
                ),
                (
                    "finalizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="denuncias_finalizadas",
                        to="usuario.usuario",
                    ),
                ),
                (
                    "recebido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="denuncias_recebidas",
                        to="usuario.usuario",
                    ),
                ),
            ],
        ),
    ]
